// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-files.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFileJournalAssociations = `-- name: DeleteFileJournalAssociations :exec
DELETE FROM file_journal
WHERE google_id = $1
`

func (q *Queries) DeleteFileJournalAssociations(ctx context.Context, googleID string) error {
	_, err := q.db.Exec(ctx, deleteFileJournalAssociations, googleID)
	return err
}

const getAllFileWikiAssociations = `-- name: GetAllFileWikiAssociations :many
SELECT file_id, wiki_id from file_wiki
`

func (q *Queries) GetAllFileWikiAssociations(ctx context.Context) ([]FileWiki, error) {
	rows, err := q.db.Query(ctx, getAllFileWikiAssociations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileWiki
	for rows.Next() {
		var i FileWiki
		if err := rows.Scan(&i.FileID, &i.WikiID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, uuid, created, filename, mimetype, size, presentation_filename, miniatures_created, sha256
FROM file
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id int32) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Filename,
		&i.Mimetype,
		&i.Size,
		&i.PresentationFilename,
		&i.MiniaturesCreated,
		&i.Sha256,
	)
	return i, err
}

const getFileBySizeAndHash = `-- name: GetFileBySizeAndHash :one
SELECT id, uuid, created, filename, mimetype, size, presentation_filename, miniatures_created, sha256
FROM file
WHERE size = $1 AND sha256 = $2 AND sha256 IS NOT NULL
LIMIT 1
`

type GetFileBySizeAndHashParams struct {
	Size   int64
	Sha256 []byte
}

func (q *Queries) GetFileBySizeAndHash(ctx context.Context, arg GetFileBySizeAndHashParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileBySizeAndHash, arg.Size, arg.Sha256)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Created,
		&i.Filename,
		&i.Mimetype,
		&i.Size,
		&i.PresentationFilename,
		&i.MiniaturesCreated,
		&i.Sha256,
	)
	return i, err
}

const getFileWikiAssociations = `-- name: GetFileWikiAssociations :many
SELECT fw.file_id, fw.wiki_id, wp.title
FROM file
INNER JOIN file_wiki AS fw
  ON file.id = fw.file_id
INNER JOIN wiki_page AS wp
  ON wp.id = fw.wiki_id
ORDER BY fw.wiki_id
`

type GetFileWikiAssociationsRow struct {
	FileID int32
	WikiID int32
	Title  string
}

func (q *Queries) GetFileWikiAssociations(ctx context.Context) ([]GetFileWikiAssociationsRow, error) {
	rows, err := q.db.Query(ctx, getFileWikiAssociations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFileWikiAssociationsRow
	for rows.Next() {
		var i GetFileWikiAssociationsRow
		if err := rows.Scan(&i.FileID, &i.WikiID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFiles = `-- name: GetFiles :many
SELECT id, uuid, created, filename, mimetype, size, presentation_filename, miniatures_created, sha256
FROM file
`

func (q *Queries) GetFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, getFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Created,
			&i.Filename,
			&i.Mimetype,
			&i.Size,
			&i.PresentationFilename,
			&i.MiniaturesCreated,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesMatchingJournals = `-- name: GetFilesMatchingJournals :many
SELECT fj.google_id, fj.file_id, f.presentation_filename
FROM file_journal AS fj
INNER JOIN file AS f
  ON (f.id = fj.file_id)
WHERE fj.google_id = ANY($1::TEXT[])
`

type GetFilesMatchingJournalsRow struct {
	GoogleID             string
	FileID               int32
	PresentationFilename string
}

func (q *Queries) GetFilesMatchingJournals(ctx context.Context, googleID []string) ([]GetFilesMatchingJournalsRow, error) {
	rows, err := q.db.Query(ctx, getFilesMatchingJournals, googleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesMatchingJournalsRow
	for rows.Next() {
		var i GetFilesMatchingJournalsRow
		if err := rows.Scan(&i.GoogleID, &i.FileID, &i.PresentationFilename); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesMissingHash = `-- name: GetFilesMissingHash :many
SELECT id, uuid, created, filename, mimetype, size, presentation_filename, miniatures_created, sha256
FROM file
WHERE sha256 IS NULL
`

func (q *Queries) GetFilesMissingHash(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesMissingHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Created,
			&i.Filename,
			&i.Mimetype,
			&i.Size,
			&i.PresentationFilename,
			&i.MiniaturesCreated,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesMissingMiniatures = `-- name: GetFilesMissingMiniatures :many
SELECT f.id, f.uuid, f.created, f.filename, f.mimetype, f.size, f.presentation_filename, f.miniatures_created, f.sha256
FROM file AS f
WHERE NOT f.miniatures_created
`

func (q *Queries) GetFilesMissingMiniatures(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesMissingMiniatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Created,
			&i.Filename,
			&i.Mimetype,
			&i.Size,
			&i.PresentationFilename,
			&i.MiniaturesCreated,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesMissingOriginalVariant = `-- name: GetFilesMissingOriginalVariant :many
SELECT f.id, f.uuid, f.created, f.filename, f.mimetype, f.size, f.presentation_filename, f.miniatures_created, f.sha256
FROM file AS f
LEFT JOIN image_variant AS iv
  ON f.id = iv.file_id
WHERE iv.file_id IS NULL
`

func (q *Queries) GetFilesMissingOriginalVariant(ctx context.Context) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesMissingOriginalVariant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Created,
			&i.Filename,
			&i.Mimetype,
			&i.Size,
			&i.PresentationFilename,
			&i.MiniaturesCreated,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageVariants = `-- name: GetImageVariants :many
SELECT iv.file_id, iv.variant, iv.filename, iv.mimetype, iv.size, iv.width, iv.height, iv.sha256
FROM file
INNER JOIN image_variant AS iv
  ON file.id = iv.file_id
ORDER BY iv.variant DESC
`

func (q *Queries) GetImageVariants(ctx context.Context) ([]ImageVariant, error) {
	rows, err := q.db.Query(ctx, getImageVariants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImageVariant
	for rows.Next() {
		var i ImageVariant
		if err := rows.Scan(
			&i.FileID,
			&i.Variant,
			&i.Filename,
			&i.Mimetype,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageVariantsMissingHash = `-- name: GetImageVariantsMissingHash :many
SELECT iv.file_id, iv.variant, iv.filename, iv.mimetype, iv.size, iv.width, iv.height, iv.sha256, f.uuid
FROM image_variant as iv
INNER JOIN file AS f
  ON iv.file_id = f.id
WHERE iv.sha256 IS NULL
`

type GetImageVariantsMissingHashRow struct {
	FileID   int32
	Variant  string
	Filename string
	Mimetype string
	Size     int32
	Width    int32
	Height   int32
	Sha256   []byte
	Uuid     string
}

func (q *Queries) GetImageVariantsMissingHash(ctx context.Context) ([]GetImageVariantsMissingHashRow, error) {
	rows, err := q.db.Query(ctx, getImageVariantsMissingHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetImageVariantsMissingHashRow
	for rows.Next() {
		var i GetImageVariantsMissingHashRow
		if err := rows.Scan(
			&i.FileID,
			&i.Variant,
			&i.Filename,
			&i.Mimetype,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.Uuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariant = `-- name: GetVariant :one
SELECT file_id, variant, filename, mimetype, size, width, height, sha256
FROM image_variant
WHERE file_id=$1 AND variant=$2
`

type GetVariantParams struct {
	FileID  int32
	Variant string
}

func (q *Queries) GetVariant(ctx context.Context, arg GetVariantParams) (ImageVariant, error) {
	row := q.db.QueryRow(ctx, getVariant, arg.FileID, arg.Variant)
	var i ImageVariant
	err := row.Scan(
		&i.FileID,
		&i.Variant,
		&i.Filename,
		&i.Mimetype,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Sha256,
	)
	return i, err
}

const insertFileJournalAssociations = `-- name: InsertFileJournalAssociations :exec
INSERT INTO file_journal (google_id, file_id) VALUES ($1, UNNEST($2::INT[])) ON CONFLICT (google_id) DO NOTHING
`

type InsertFileJournalAssociationsParams struct {
	GoogleID string
	FileID   []int32
}

func (q *Queries) InsertFileJournalAssociations(ctx context.Context, arg InsertFileJournalAssociationsParams) error {
	_, err := q.db.Exec(ctx, insertFileJournalAssociations, arg.GoogleID, arg.FileID)
	return err
}

const publishFile = `-- name: PublishFile :one
INSERT
INTO file
  (uuid, created, filename, presentation_filename, mimetype, size, sha256)
VALUES 
  ($1, $2, $3, $3, $4, $5, $6)
RETURNING id
`

type PublishFileParams struct {
	Uuid     string
	Created  pgtype.Timestamptz
	Filename string
	Mimetype string
	Size     int64
	Sha256   []byte
}

func (q *Queries) PublishFile(ctx context.Context, arg PublishFileParams) (int32, error) {
	row := q.db.QueryRow(ctx, publishFile,
		arg.Uuid,
		arg.Created,
		arg.Filename,
		arg.Mimetype,
		arg.Size,
		arg.Sha256,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const publishVariant = `-- name: PublishVariant :exec
INSERT
INTO image_variant
  (file_id, variant, filename, mimetype, size, width, height, sha256)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8)
`

type PublishVariantParams struct {
	FileID   int32
	Variant  string
	Filename string
	Mimetype string
	Size     int32
	Width    int32
	Height   int32
	Sha256   []byte
}

func (q *Queries) PublishVariant(ctx context.Context, arg PublishVariantParams) error {
	_, err := q.db.Exec(ctx, publishVariant,
		arg.FileID,
		arg.Variant,
		arg.Filename,
		arg.Mimetype,
		arg.Size,
		arg.Width,
		arg.Height,
		arg.Sha256,
	)
	return err
}

const removeFalseFileWikiLinks = `-- name: RemoveFalseFileWikiLinks :execresult
with unused as (
    select fw.file_id, fw.wiki_id
    from file_wiki fw
    left join wiki_revision wr
      on wr.page_id = fw.wiki_id
         and wr.content @? (
               ('$.blocks[*].data.file.url ? (@ like_regex "^/file/' || fw.file_id || '")')::jsonpath
           )
    where wr.page_id is null
)
delete from file_wiki fw
using unused u
where fw.file_id = u.file_id
  and fw.wiki_id = u.wiki_id
`

func (q *Queries) RemoveFalseFileWikiLinks(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, removeFalseFileWikiLinks)
}

const setFileHash = `-- name: SetFileHash :exec
UPDATE file
SET sha256 = $2
WHERE id = $1
`

type SetFileHashParams struct {
	ID     int32
	Sha256 []byte
}

func (q *Queries) SetFileHash(ctx context.Context, arg SetFileHashParams) error {
	_, err := q.db.Exec(ctx, setFileHash, arg.ID, arg.Sha256)
	return err
}

const setImageVariantHash = `-- name: SetImageVariantHash :exec
UPDATE image_variant
SET sha256 = $3
WHERE file_id = $1 AND variant = $2
`

type SetImageVariantHashParams struct {
	FileID  int32
	Variant string
	Sha256  []byte
}

func (q *Queries) SetImageVariantHash(ctx context.Context, arg SetImageVariantHashParams) error {
	_, err := q.db.Exec(ctx, setImageVariantHash, arg.FileID, arg.Variant, arg.Sha256)
	return err
}

const setMiniaturesCreated = `-- name: SetMiniaturesCreated :exec
UPDATE file
SET miniatures_created=TRUE
WHERE id = $1
`

func (q *Queries) SetMiniaturesCreated(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setMiniaturesCreated, id)
	return err
}

const unpublishFile = `-- name: UnpublishFile :exec
DELETE
FROM file
WHERE id = $1
`

func (q *Queries) UnpublishFile(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, unpublishFile, id)
	return err
}

const updatePresentationFilename = `-- name: UpdatePresentationFilename :exec
UPDATE file
SET presentation_filename = $1
WHERE id = $2
`

type UpdatePresentationFilenameParams struct {
	Filename string
	ID       int32
}

func (q *Queries) UpdatePresentationFilename(ctx context.Context, arg UpdatePresentationFilenameParams) error {
	_, err := q.db.Exec(ctx, updatePresentationFilename, arg.Filename, arg.ID)
	return err
}
