// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-stat-debug.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const statDebugGet = `-- name: StatDebugGet :many
SELECT time, key, value
FROM stat_debug
WHERE key = ANY($1::smallint[])
  AND time >= $2::timestamptz
  AND time <= $3::timestamptz
ORDER BY key, time
`

type StatDebugGetParams struct {
	Keys  []int16
	Start pgtype.Timestamptz
	Stop  pgtype.Timestamptz
}

type StatDebugGetRow struct {
	Time  pgtype.Timestamptz
	Key   int16
	Value float32
}

func (q *Queries) StatDebugGet(ctx context.Context, arg StatDebugGetParams) ([]StatDebugGetRow, error) {
	rows, err := q.db.Query(ctx, statDebugGet, arg.Keys, arg.Start, arg.Stop)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatDebugGetRow
	for rows.Next() {
		var i StatDebugGetRow
		if err := rows.Scan(&i.Time, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statDebugInsert = `-- name: StatDebugInsert :execrows
INSERT INTO stat_debug (time, key, value)
SELECT
  $1::timestamptz,
  k.key,
  v.value
FROM unnest($2::smallint[]) WITH ORDINALITY AS k(key, ord)
JOIN unnest($3::real[])     WITH ORDINALITY AS v(value, ord)
USING (ord)
`

type StatDebugInsertParams struct {
	Time  pgtype.Timestamptz
	Key   []int16
	Value []float32
}

func (q *Queries) StatDebugInsert(ctx context.Context, arg StatDebugInsertParams) (int64, error) {
	result, err := q.db.Exec(ctx, statDebugInsert, arg.Time, arg.Key, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
