// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-syslog.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sysLogDrop = `-- name: SysLogDrop :execrows
DELETE
FROM syslog
WHERE time < NOW() - $1
`

func (q *Queries) SysLogDrop(ctx context.Context, threshold interface{}) (int64, error) {
	result, err := q.db.Exec(ctx, sysLogDrop, threshold)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sysLogGet = `-- name: SysLogGet :many
SELECT id, message, severity, time
FROM syslog
ORDER BY id DESC
LIMIT $2
OFFSET $1
`

type SysLogGetParams struct {
	Offs int32
	Lim  int32
}

func (q *Queries) SysLogGet(ctx context.Context, arg SysLogGetParams) ([]Syslog, error) {
	rows, err := q.db.Query(ctx, sysLogGet, arg.Offs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Syslog
	for rows.Next() {
		var i Syslog
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.Severity,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sysLogInsert = `-- name: SysLogInsert :exec
INSERT INTO syslog (
    message,
    severity,
    time
) VALUES (
    $1,
    $2,
    $3
)
`

type SysLogInsertParams struct {
	Message  string
	Severity int32
	Time     pgtype.Timestamptz
}

func (q *Queries) SysLogInsert(ctx context.Context, arg SysLogInsertParams) error {
	_, err := q.db.Exec(ctx, sysLogInsert, arg.Message, arg.Severity, arg.Time)
	return err
}
