// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-division.sql

package sql

import (
	"context"
)

const deleteDivision = `-- name: DeleteDivision :exec
DELETE FROM division WHERE id = $1
`

func (q *Queries) DeleteDivision(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDivision, id)
	return err
}

const getDivisions = `-- name: GetDivisions :many
SELECT id, name FROM division
ORDER BY id ASC
`

func (q *Queries) GetDivisions(ctx context.Context) ([]Division, error) {
	rows, err := q.db.Query(ctx, getDivisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Division
	for rows.Next() {
		var i Division
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDivision = `-- name: InsertDivision :exec
INSERT INTO division (name) VALUES ($1)
`

func (q *Queries) InsertDivision(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertDivision, name)
	return err
}

const setDivisionName = `-- name: SetDivisionName :exec
UPDATE division SET name = $2 WHERE id = $1
`

type SetDivisionNameParams struct {
	ID   int32
	Name string
}

func (q *Queries) SetDivisionName(ctx context.Context, arg SetDivisionNameParams) error {
	_, err := q.db.Exec(ctx, setDivisionName, arg.ID, arg.Name)
	return err
}
