// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-job.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobLastSuccess = `-- name: GetJobLastSuccess :one
SELECT last_success FROM job WHERE name = $1
`

func (q *Queries) GetJobLastSuccess(ctx context.Context, name string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getJobLastSuccess, name)
	var last_success pgtype.Timestamptz
	err := row.Scan(&last_success)
	return last_success, err
}

const markJobCompleted = `-- name: MarkJobCompleted :exec
INSERT INTO job (name, last_success) VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET last_success = EXCLUDED.last_success
`

type MarkJobCompletedParams struct {
	Name        string
	LastSuccess pgtype.Timestamptz
}

func (q *Queries) MarkJobCompleted(ctx context.Context, arg MarkJobCompletedParams) error {
	_, err := q.db.Exec(ctx, markJobCompleted, arg.Name, arg.LastSuccess)
	return err
}
