// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-division.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToHome = `-- name: AddUserToHome :exec
UPDATE appuser
SET home_id = $1
WHERE id = $2
`

type AddUserToHomeParams struct {
	HomeID pgtype.Int4
	ID     int32
}

func (q *Queries) AddUserToHome(ctx context.Context, arg AddUserToHomeParams) error {
	_, err := q.db.Exec(ctx, addUserToHome, arg.HomeID, arg.ID)
	return err
}

const deleteDivision = `-- name: DeleteDivision :exec
DELETE FROM division WHERE id = $1
`

func (q *Queries) DeleteDivision(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDivision, id)
	return err
}

const getDivisionJournalFolderForAppUser = `-- name: GetDivisionJournalFolderForAppUser :one
SELECT 'TEST'
FROM appuser
WHERE id = $1
`

func (q *Queries) GetDivisionJournalFolderForAppUser(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getDivisionJournalFolderForAppUser, id)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getDivisionJournalFolderForHome = `-- name: GetDivisionJournalFolderForHome :one

SELECT d.journal_folder_id
FROM home AS h
LEFT JOIN division AS d
    ON h.division_id = d.id
WHERE h.id = $1
`

// TODO
func (q *Queries) GetDivisionJournalFolderForHome(ctx context.Context, id int32) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getDivisionJournalFolderForHome, id)
	var journal_folder_id pgtype.Text
	err := row.Scan(&journal_folder_id)
	return journal_folder_id, err
}

const getDivisions = `-- name: GetDivisions :many
SELECT id, name, journal_folder_id, journal_folder_name, template_journal_id, template_journal_name FROM division
ORDER BY id ASC
`

func (q *Queries) GetDivisions(ctx context.Context) ([]Division, error) {
	rows, err := q.db.Query(ctx, getDivisions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Division
	for rows.Next() {
		var i Division
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.JournalFolderID,
			&i.JournalFolderName,
			&i.TemplateJournalID,
			&i.TemplateJournalName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDivision = `-- name: InsertDivision :exec
INSERT INTO division (name) VALUES ($1)
`

func (q *Queries) InsertDivision(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, insertDivision, name)
	return err
}

const removeUserFromHome = `-- name: RemoveUserFromHome :exec
UPDATE appuser
SET home_id = 0
WHERE home_id = $1
  AND id = $2
`

type RemoveUserFromHomeParams struct {
	HomeID pgtype.Int4
	ID     int32
}

func (q *Queries) RemoveUserFromHome(ctx context.Context, arg RemoveUserFromHomeParams) error {
	_, err := q.db.Exec(ctx, removeUserFromHome, arg.HomeID, arg.ID)
	return err
}

const setDivisionJournalFolder = `-- name: SetDivisionJournalFolder :exec
UPDATE division
SET journal_folder_id = $2, journal_folder_name = $3
WHERE id = $1
`

type SetDivisionJournalFolderParams struct {
	ID                int32
	JournalFolderID   pgtype.Text
	JournalFolderName pgtype.Text
}

func (q *Queries) SetDivisionJournalFolder(ctx context.Context, arg SetDivisionJournalFolderParams) error {
	_, err := q.db.Exec(ctx, setDivisionJournalFolder, arg.ID, arg.JournalFolderID, arg.JournalFolderName)
	return err
}

const setDivisionName = `-- name: SetDivisionName :exec
UPDATE division SET name = $2 WHERE id = $1
`

type SetDivisionNameParams struct {
	ID   int32
	Name string
}

func (q *Queries) SetDivisionName(ctx context.Context, arg SetDivisionNameParams) error {
	_, err := q.db.Exec(ctx, setDivisionName, arg.ID, arg.Name)
	return err
}

const setDivisionTemplateJournal = `-- name: SetDivisionTemplateJournal :exec
UPDATE division
SET template_journal_id = $2, template_journal_name = $3
WHERE id = $1
`

type SetDivisionTemplateJournalParams struct {
	ID                  int32
	TemplateJournalID   pgtype.Text
	TemplateJournalName pgtype.Text
}

func (q *Queries) SetDivisionTemplateJournal(ctx context.Context, arg SetDivisionTemplateJournalParams) error {
	_, err := q.db.Exec(ctx, setDivisionTemplateJournal, arg.ID, arg.TemplateJournalID, arg.TemplateJournalName)
	return err
}
