// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-user.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAllUserGDriveAccess = `-- name: ClearAllUserGDriveAccess :exec
UPDATE appuser
SET has_gdrive_access = FALSE
WHERE 1
`

func (q *Queries) ClearAllUserGDriveAccess(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAllUserGDriveAccess)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO appuser (
  display_name,
  google_sub,
  email, 
  avatar_url,
  access_level,
  home_id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id
`

type CreateUserParams struct {
	DisplayName string
	GoogleSub   string
	Email       string
	AvatarUrl   pgtype.Text
	AccessLevel int32
	HomeID      pgtype.Int4
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.DisplayName,
		arg.GoogleSub,
		arg.Email,
		arg.AvatarUrl,
		arg.AccessLevel,
		arg.HomeID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteAppuser = `-- name: DeleteAppuser :exec
DELETE
FROM appuser
WHERE id = $1
`

func (q *Queries) DeleteAppuser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAppuser, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE
FROM session
WHERE appuser_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, appuserID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, appuserID)
	return err
}

const getAppusers = `-- name: GetAppusers :many
SELECT id, display_name, google_sub, email, logging_consent, avatar_url, has_gdrive_access, access_level, language_id, home_id
FROM appuser
ORDER BY id
`

func (q *Queries) GetAppusers(ctx context.Context) ([]Appuser, error) {
	rows, err := q.db.Query(ctx, getAppusers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appuser
	for rows.Next() {
		var i Appuser
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GoogleSub,
			&i.Email,
			&i.LoggingConsent,
			&i.AvatarUrl,
			&i.HasGdriveAccess,
			&i.AccessLevel,
			&i.LanguageID,
			&i.HomeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppusersForHome = `-- name: GetAppusersForHome :many
SELECT id, display_name, google_sub, email, logging_consent, avatar_url, has_gdrive_access, access_level, language_id, home_id
FROM appuser
WHERE home_id = $1
`

func (q *Queries) GetAppusersForHome(ctx context.Context, homeID pgtype.Int4) ([]Appuser, error) {
	rows, err := q.db.Query(ctx, getAppusersForHome, homeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appuser
	for rows.Next() {
		var i Appuser
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GoogleSub,
			&i.Email,
			&i.LoggingConsent,
			&i.AvatarUrl,
			&i.HasGdriveAccess,
			&i.AccessLevel,
			&i.LanguageID,
			&i.HomeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppusersInDivision = `-- name: GetAppusersInDivision :many
SELECT au.id, au.display_name, au.google_sub, au.email, au.logging_consent, au.avatar_url, au.has_gdrive_access, au.access_level, au.language_id, au.home_id
FROM appuser AS au
LEFT JOIN home AS h
  ON h.id = au.home_id
WHERE h.division = $1
ORDER BY au.id
`

func (q *Queries) GetAppusersInDivision(ctx context.Context, division int32) ([]Appuser, error) {
	rows, err := q.db.Query(ctx, getAppusersInDivision, division)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appuser
	for rows.Next() {
		var i Appuser
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.GoogleSub,
			&i.Email,
			&i.LoggingConsent,
			&i.AvatarUrl,
			&i.HasGdriveAccess,
			&i.AccessLevel,
			&i.LanguageID,
			&i.HomeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHomeForUser = `-- name: GetHomeForUser :one
SELECT h.id, h.name, h.capacity, h.note, h.division 
FROM appuser AS a
INNER JOIN home AS h
  ON h.id = a.home_id
WHERE a.id = $1
`

func (q *Queries) GetHomeForUser(ctx context.Context, id int32) (Home, error) {
	row := q.db.QueryRow(ctx, getHomeForUser, id)
	var i Home
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.Note,
		&i.Division,
	)
	return i, err
}

const getHomeWithDataForUser = `-- name: GetHomeWithDataForUser :one
SELECT h.id, h.name, h.capacity, h.note, h.division
FROM appuser AS a
INNER JOIN home AS h
  ON h.id = a.id
WHERE a.id = $1
`

func (q *Queries) GetHomeWithDataForUser(ctx context.Context, id int32) (Home, error) {
	row := q.db.QueryRow(ctx, getHomeWithDataForUser, id)
	var i Home
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.Note,
		&i.Division,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, google_sub, email, logging_consent, avatar_url, has_gdrive_access, access_level, language_id, home_id
FROM appuser
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (Appuser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i Appuser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.GoogleSub,
		&i.Email,
		&i.LoggingConsent,
		&i.AvatarUrl,
		&i.HasGdriveAccess,
		&i.AccessLevel,
		&i.LanguageID,
		&i.HomeID,
	)
	return i, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id
FROM appuser
WHERE email = $1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUsersWithGoogleStoredAvatars = `-- name: GetUsersWithGoogleStoredAvatars :many
SELECT id, avatar_url
FROM appuser
WHERE avatar_url LIKE '%googleusercontent.com%'
`

type GetUsersWithGoogleStoredAvatarsRow struct {
	ID        int32
	AvatarUrl pgtype.Text
}

func (q *Queries) GetUsersWithGoogleStoredAvatars(ctx context.Context) ([]GetUsersWithGoogleStoredAvatarsRow, error) {
	rows, err := q.db.Query(ctx, getUsersWithGoogleStoredAvatars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWithGoogleStoredAvatarsRow
	for rows.Next() {
		var i GetUsersWithGoogleStoredAvatarsRow
		if err := rows.Scan(&i.ID, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeHomeForAppuser = `-- name: RemoveHomeForAppuser :exec
UPDATE appuser
SET home_id = 0
WHERE id = $1
`

func (q *Queries) RemoveHomeForAppuser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, removeHomeForAppuser, id)
	return err
}

const revokeLoggingConsent = `-- name: RevokeLoggingConsent :exec
UPDATE appuser SET logging_consent = NULL
WHERE id = $1
`

func (q *Queries) RevokeLoggingConsent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revokeLoggingConsent, id)
	return err
}

const scrubAppuser = `-- name: ScrubAppuser :exec
UPDATE appuser SET
  display_name = 'Deleted user (id = ' || id || ')',
  google_sub = '',
  email = '',
  logging_consent = NULL,
  avatar_url = '',
  has_gdrive_access = FALSE 
WHERE id = $1
`

func (q *Queries) ScrubAppuser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, scrubAppuser, id)
	return err
}

const setLoggingConsent = `-- name: SetLoggingConsent :exec
UPDATE appuser SET logging_consent = NOW() + $2::INT * INTERVAL '1 day'
WHERE id = $1
`

type SetLoggingConsentParams struct {
	ID     int32
	Period int32
}

func (q *Queries) SetLoggingConsent(ctx context.Context, arg SetLoggingConsentParams) error {
	_, err := q.db.Exec(ctx, setLoggingConsent, arg.ID, arg.Period)
	return err
}

const setUserGDriveAccess = `-- name: SetUserGDriveAccess :exec
UPDATE appuser
SET has_gdrive_access = $2
WHERE id = $1
`

type SetUserGDriveAccessParams struct {
	ID              int32
	HasGdriveAccess bool
}

func (q *Queries) SetUserGDriveAccess(ctx context.Context, arg SetUserGDriveAccessParams) error {
	_, err := q.db.Exec(ctx, setUserGDriveAccess, arg.ID, arg.HasGdriveAccess)
	return err
}

const setUserLanguage = `-- name: SetUserLanguage :exec
UPDATE appuser
SET language_id = $2
WHERE id = $1
`

type SetUserLanguageParams struct {
	ID         int32
	LanguageID pgtype.Int4
}

func (q *Queries) SetUserLanguage(ctx context.Context, arg SetUserLanguageParams) error {
	_, err := q.db.Exec(ctx, setUserLanguage, arg.ID, arg.LanguageID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE appuser
SET display_name = $3,
    google_sub = $4,
    avatar_url = $5
WHERE id = $1
  AND email = $2
`

type UpdateUserParams struct {
	ID          int32
	Email       string
	DisplayName string
	GoogleSub   string
	AvatarUrl   pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.GoogleSub,
		arg.AvatarUrl,
	)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE appuser
SET avatar_url = $1
WHERE id = $2
`

type UpdateUserAvatarParams struct {
	Url pgtype.Text
	ID  int32
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.Url, arg.ID)
	return err
}
