// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sql-journal.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteJournal = `-- name: DeleteJournal :exec
DELETE
FROM journal
WHERE google_id = $1
`

func (q *Queries) DeleteJournal(ctx context.Context, googleID string) error {
	_, err := q.db.Exec(ctx, deleteJournal, googleID)
	return err
}

const getGoogleFolder = `-- name: GetGoogleFolder :one
SELECT google_id, name
FROM google_folder
WHERE google_id = $1
`

func (q *Queries) GetGoogleFolder(ctx context.Context, googleID string) (GoogleFolder, error) {
	row := q.db.QueryRow(ctx, getGoogleFolder, googleID)
	var i GoogleFolder
	err := row.Scan(&i.GoogleID, &i.Name)
	return i, err
}

const getJournalImageURLs = `-- name: GetJournalImageURLs :one
SELECT image_urls
FROM journal
WHERE google_id = $1
`

func (q *Queries) GetJournalImageURLs(ctx context.Context, googleID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getJournalImageURLs, googleID)
	var image_urls []byte
	err := row.Scan(&image_urls)
	return image_urls, err
}

const getJournalJSON = `-- name: GetJournalJSON :one
SELECT updated, parent_google_id, gf.name AS parent_google_name, raw_json, image_urls, edited_json
FROM journal
LEFT JOIN google_folder AS gf
    ON gf.google_id = journal.parent_google_id
WHERE journal.google_id = $1
`

type GetJournalJSONRow struct {
	Updated          pgtype.Timestamptz
	ParentGoogleID   pgtype.Text
	ParentGoogleName pgtype.Text
	RawJson          []byte
	ImageUrls        []byte
	EditedJson       []byte
}

func (q *Queries) GetJournalJSON(ctx context.Context, googleID string) (GetJournalJSONRow, error) {
	row := q.db.QueryRow(ctx, getJournalJSON, googleID)
	var i GetJournalJSONRow
	err := row.Scan(
		&i.Updated,
		&i.ParentGoogleID,
		&i.ParentGoogleName,
		&i.RawJson,
		&i.ImageUrls,
		&i.EditedJson,
	)
	return i, err
}

const getJournalMetadata = `-- name: GetJournalMetadata :one
SELECT j.updated, j.parent_google_id, gf.name AS parent_google_name, j.version
FROM journal AS j
LEFT JOIN google_folder AS gf
    ON gf.google_id = j.parent_google_id
WHERE j.google_id = $1
`

type GetJournalMetadataRow struct {
	Updated          pgtype.Timestamptz
	ParentGoogleID   pgtype.Text
	ParentGoogleName pgtype.Text
	Version          int16
}

func (q *Queries) GetJournalMetadata(ctx context.Context, googleID string) (GetJournalMetadataRow, error) {
	row := q.db.QueryRow(ctx, getJournalMetadata, googleID)
	var i GetJournalMetadataRow
	err := row.Scan(
		&i.Updated,
		&i.ParentGoogleID,
		&i.ParentGoogleName,
		&i.Version,
	)
	return i, err
}

const getJournalsUpdatedAfter = `-- name: GetJournalsUpdatedAfter :many
SELECT google_id, raw_json, image_urls
FROM journal
WHERE updated > $1
ORDER BY updated ASC
`

type GetJournalsUpdatedAfterRow struct {
	GoogleID  string
	RawJson   []byte
	ImageUrls []byte
}

func (q *Queries) GetJournalsUpdatedAfter(ctx context.Context, updated pgtype.Timestamptz) ([]GetJournalsUpdatedAfterRow, error) {
	rows, err := q.db.Query(ctx, getJournalsUpdatedAfter, updated)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJournalsUpdatedAfterRow
	for rows.Next() {
		var i GetJournalsUpdatedAfterRow
		if err := rows.Scan(&i.GoogleID, &i.RawJson, &i.ImageUrls); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveGoogleFolder = `-- name: SaveGoogleFolder :exec
INSERT INTO google_folder (google_id, name)
VALUES ($1, $2)
ON CONFLICT (google_id) DO UPDATE
    SET name=EXCLUDED.name
`

type SaveGoogleFolderParams struct {
	GoogleID string
	Name     string
}

func (q *Queries) SaveGoogleFolder(ctx context.Context, arg SaveGoogleFolderParams) error {
	_, err := q.db.Exec(ctx, saveGoogleFolder, arg.GoogleID, arg.Name)
	return err
}

const setGoogleParentFolder = `-- name: SetGoogleParentFolder :exec
UPDATE journal
SET parent_google_id = $2
WHERE google_id = $1
`

type SetGoogleParentFolderParams struct {
	GoogleID       string
	ParentGoogleID pgtype.Text
}

func (q *Queries) SetGoogleParentFolder(ctx context.Context, arg SetGoogleParentFolderParams) error {
	_, err := q.db.Exec(ctx, setGoogleParentFolder, arg.GoogleID, arg.ParentGoogleID)
	return err
}

const updateJournalEdited = `-- name: UpdateJournalEdited :exec
UPDATE journal
SET edited_json = $2
WHERE google_id = $1
`

type UpdateJournalEditedParams struct {
	GoogleID   string
	EditedJson []byte
}

func (q *Queries) UpdateJournalEdited(ctx context.Context, arg UpdateJournalEditedParams) error {
	_, err := q.db.Exec(ctx, updateJournalEdited, arg.GoogleID, arg.EditedJson)
	return err
}

const upsertJournal = `-- name: UpsertJournal :exec
INSERT INTO journal (
    google_id,
    origin,
    parent_google_id,
    updated,
    raw_json,
    image_urls,
    lang,
    header,
    body,
    version
)
VALUES (
    $1,
    $2,
    $3,
    NOW(),
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (google_id) DO UPDATE
    SET updated=NOW(),
        origin=EXCLUDED.origin,
        parent_google_id=EXCLUDED.parent_google_id,
        raw_json=EXCLUDED.raw_json,
        image_urls=EXCLUDED.image_urls,
        lang=EXCLUDED.lang,
        header=EXCLUDED.header,
        body=EXCLUDED.body,
        version=EXCLUDED.version
`

type UpsertJournalParams struct {
	GoogleID       string
	Origin         int16
	ParentGoogleID pgtype.Text
	RawJson        []byte
	ImageUrls      []byte
	Lang           interface{}
	Header         pgtype.Text
	Body           pgtype.Text
	Version        int16
}

func (q *Queries) UpsertJournal(ctx context.Context, arg UpsertJournalParams) error {
	_, err := q.db.Exec(ctx, upsertJournal,
		arg.GoogleID,
		arg.Origin,
		arg.ParentGoogleID,
		arg.RawJson,
		arg.ImageUrls,
		arg.Lang,
		arg.Header,
		arg.Body,
		arg.Version,
	)
	return err
}
