-- +migrate Up
ALTER TABLE file ADD COLUMN filename TEXT   NOT NULL DEFAULT '';
ALTER TABLE file ADD COLUMN mimetype TEXT   NOT NULL DEFAULT '';
ALTER TABLE file ADD COLUMN size     BIGINT NOT NULL DEFAULT 0;
